apiVersion: 1
kind: DaemonSet 
metadata: 
  name: watchman
  namespace: the-kube-way
  labels: 
    app: watchman
spec:
  template:
    metadata:
      labels: 
        app: watchman
      spec:
        containers: 
        - name: watchman
          image:andrewpsp/watchman
          resources:
            limits:
              memory: 300Mi 
            requests: 
              cpu: 100m
              memory: 200Mi 
          volumeMounts:
          - name: the-kube-way-log
            mountPath: /opt/watchman
            readOnly: true 
          terminationGracePeriodSeconds: 45
          volumes:
           - name: the-kube-way-log
             hostpath: 
               path: /opt/watchman
               
        
